.template_repo: &repo
  project: "devops/ci/templates"
  ref: &ci_tmpl_vers $CI_TMPL_V3_PORTALS

.qa_ci_templates: &qatempls
  project: "portals/qa-automation/qa-ci-templates"
  ref: master
  file: /frontend/frontend_complex.yml

variables:
  # hold pls
  CI_TMPL_PROJECT_VERSION: *ci_tmpl_vers
  CI_TMPL_DEVELOPMENT_FLOW: "TBD"
  # ci vars
  DOCKERFILE_DIR: ./config/deploy/docker
  # test image
  UNIVERSAL_IMAGE: harbor.wildberries.ru/portal-shared/frontend/frontend-services-node
  UNIVERSAL_VER: "v18.9.0"
  # list of services for build & deploy
  CI_TMPL_HELM_RELEASE_NAMES: "feedback-questions-front"
  CI_TMPL_HELM_RELEASE_NAMESPACE: frontend-services
  CI_TMPL_HELM_CHARTS: "common-deploy@v$PORTALS_COMMON_DEPLOY_V4_VERSION"
  # front vars
  APP_STATIC_NAMESPACE: feedback-questions-front
  WB_STATIC_URL: $WB_STATIC_URL_GROUP_VAR
  SERVICE_URL: $SERVICE_URL_GROUP_VAR
  GATSBY_SENTRY_RELEASE: ${CI_COMMIT_TAG}
  MAKEFILEPATH: ./config/deploy/Makefile

  CI_TMPL_HELM_CUSTOM_MENU_AUTH_TOKEN_STAGE: $MENU_AUTH_TOKEN_STAGE
  CI_TMPL_HELM_CUSTOM_MENU_AUTH_TOKEN_PROD: $MENU_AUTH_TOKEN_PROD

  REGISTRY_PROJECT: portal-frontend-services

  BUILD_CUSTOM_ARGS: "CI_COMMIT_TAG=$CI_COMMIT_TAG,REACT_APP_YANDEX_KEY=$REACT_APP_YANDEX_KEY,APP_STATIC_NAMESPACE=$APP_STATIC_NAMESPACE,CDN_API_TOKEN=$CDN_API_TOKEN,WB_STATIC_URL=$WB_STATIC_URL,SERVICE_URL=$SERVICE_URL,BUCKET=$BUCKET"

stages:
  - checks
  - frontend_complex
  - generate dynamic pipeline
  - external ci
  - build
  - deploy

frontend_complex:
  image: ${UNIVERSAL_IMAGE}:${UNIVERSAL_VER}
  stage: frontend_complex
  allow_failure: false
  script:
    - make -f ${MAKEFILEPATH} frontend_complex
    - cat coverage/text-summary.txt
  coverage: '/Lines\s*:\s*(\d+.?\d*)%/'
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - coverage/coverage-summary.json
      - coverage/cobertura-coverage.xml
      - coverage/junit.xml
    reports:
      coverage_report:
          coverage_format: cobertura
          path: coverage/cobertura-coverage.xml
      junit:
        - coverage/junit.xml

include:
  - {<<: *repo, file: /pipelines/universal.yml}
  - {<<: *qatempls}
